name = "Newsroom"
license = "MIT"
licenselink = "https://github.com/onweru/hugo-newsroom-theme/blob/master/LICENSE.md"
description = "A simple open source theme for publishing multi-purpose content"
homepage = "https://github.com/onweru/hugo-newsroom-theme"
tags = ["blog", "simple", "dark", "minimalist", "fast", "light", "modern"]
features = ["blog", "simple", "dark", "minimalist", "fast", "light", "modern"]
min_version = 0.42

[author]
    name ="weru"
    homepage = "https://github.com/onweru/hugo-newsroom-theme"
